@extends('layouts.app')
@section('content')
    @auth('artists')
        @include('artist.auth.auth')
    @endauth
    @guest('artists')
        @include('artist.guest.guest')
    @endguest
@endsection